### PR TITLE
Update to use go modules

### PR DESCRIPTION
**Pull request by utzig**

### CODE REVIEW

**Comment by utzig** [comment]
@ccollins476ad So I had to add a `replace` directive here because `newt` and `newtmgr` have conflicting `go-codec` deps. The other solution would be to update both of them to a fixed version (say last release `v1.1.7`). What do you think?

**Comment by ccollins476ad** [comment]
@utzig I think we should modify both to use 1.1.7.  Go modules seem to be built around the idea that packages are versioned.  If you would rather use `replace`, then I think that is OK as well.

**Comment by utzig** [comment]
@ccollins476ad Done https://github.com/apache/mynewt-newt/pull/314, https://github.com/apache/mynewt-newtmgr/pull/131

**Comment by utzig** [comment]
@ccollins476ad Btw, I know `replace` works because I can build with it, but I am hoping that the changes  to `newt` and `newtmgr` allow me to remove it, but I don't know how to test such multi repo changes offline!

**Comment by ccollins476ad** [comment]
I think the only way to test such changes offline is with more `replace` directives :).

**Comment by utzig** [comment]
Updated, `replace` removed.

**Comment by ccollins476ad** [comment]
When I try building this branch, `go.sum` gets automatically updated:
```
diff --git a/go.sum b/go.sum
index 60d0a7c..9b7f752 100644
--- a/go.sum
+++ b/go.sum
@@ -50,6 +50,7 @@ github.com/pkg/errors v0.8.0/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINE
 github.com/pkg/errors v0.8.1 h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
 github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
 github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
+github.com/raff/goble v0.0.0-20170814221208-b12b34f940c4 h1:wa4KKsyv+e7TmpzAfp+TWXG+3s/ZWaQ4QsVqMU5oUrk=
 github.com/raff/goble v0.0.0-20170814221208-b12b34f940c4/go.mod h1:CxaUhijgLFX0AROtH5mluSY71VqpjQBw9JXE2UKZmc4=
 github.com/runtimeco/go-coap v0.0.0-20180109101419-47c23e2a63ea h1:zTOcylKcdobkyW4gySyvvHkAGnOP0QNcGaO0ZQJFgxQ=
 github.com/runtimeco/go-coap v0.0.0-20180109101419-47c23e2a63ea/go.mod h1:x/rLuxedbWFDN497ZirUaDklkWz6JhZLjGdgurMysxM=
```

I don't really understand the addition, but I assume it is innocuous.  Maybe you just need to build one last time and then commit the updated `go.sum`.

**Comment by utzig** [comment]
I haven't seen it actually, I just deleted `go.mod` and `go.sum` and regenerated/rebuilt!

**Comment by utzig** [comment]
@ccollins476ad Oops, sorry did not understand; I am not sure why this is happening TBH, but I assume it should happen here as well...

**Comment by utzig** [comment]
btw I have `go version go1.12.7 linux/amd64` here, what's yours?

**Comment by utzig** [comment]
@ccollins476ad Ok, so I tried adding that line and building and `go build` did not remove it, so I just left it there! Please check again that your build system does not change it.

**Review by ccollins476ad — APPROVED** [review]

**Pull request merged**
